### ISSUE TITLE
[NF] Make the plugin available for t9n

### ISSUE THREAD

**Issue by MATsxm** [robgnu/grav-plugin-subscriber#1]
Hi,
Great work.
Why not adding a language file for labels and default messages?
This way would make it easy available for translation.
Ping me for the :fr: version if you need
Thanks

**Comment by robgnu** [comment]
Thank you for your suggestion. I hope to do this in near future. I would be glad to get your help. I will ping you.

**Comment by robgnu** [comment]
@MATsxm I've released a new version of this plugin. Now there is a languages.yaml file. Thank you for your offer helping in translation. If you like, I would be happy about your help. (Ping)
