### ISSUE TITLE
Error displaying the thank you message

### ISSUE THREAD

**Issue by rissson** [robgnu/grav-plugin-subscriber#5]
![image](https://cloud.githubusercontent.com/assets/18313093/26471951/3c4e02f4-41a4-11e7-81a9-557819a30d77.png)
Hi !, here's what I get after a subscription...

**Comment by karfau** [comment]
- What is the language that you have configured in your page?
- Is this only happeing for this message or also for the other messages?

**Comment by rissson** [comment]
- French is the language for the whole website 
- I don't know, what are the other messages ? Afaik it does it for subscribe and unsubscribe

**Comment by karfau** [comment]
(Assuming you followed the [Setup instructions](https://github.com/robgnu/grav-plugin-subscriber#setup))
A copy of the `languages:` section of your `user/config/system.yaml` would be helpful in helping you to debug.

**Comment by rissson** [comment]
I did follow the Setup instructions,
Here is the `languages:` section of my `user/config/system.yaml`
`
languages:  
  supported:  
    - fr  
  include_default_lang: false
  translations: false
  translations_fallback: true
  session_store_active: true
  http_accept_language: true
  override_locale: false
`

**Comment by karfau** [comment]
As far as I understand [these docs](https://learn.getgrav.org/content/multi-language#translation-support) you need to set `system.languages.translations` to **`true`** to be able to get translated stings.

Can you try to set it to true and see if it helps?

**Comment by robgnu** [comment]
Sorry for the late delay. Is the problem solved or is there still need for help? Please let me know.
