### ISSUE TITLE
Question about adding MailChimp integration

### ISSUE THREAD

**Issue by karfau** [robgnu/grav-plugin-subscriber#6]
Hey there,

I'm currently setting up integration with Mailchimp on a page I'm preparing.

Would you like to see a PR with an option for integration (in case I'm able to achieve it ;) ),
Or would you prefer to see a plugin that does just the MailChimp thing?

Best Christian

**Comment by robgnu** [comment]
Hello Christian,
I don't use Mailchimp, but if you have any code that works, you can send a PR. Every part that makes this plugin better is a good part. :) I think a option for turning on/off is the way to go.
Best, Rob
